### PR TITLE
Update .travis.yml with new template

### LINKED ISSUE #6: Update travis for conda
- the new travis boilerplate should be in the slack

### PR DESCRIPTION
**Pull request by kcpearce**
# Key Points:
  - [x] Uses new .travis.yml template for conda that Daniel Smith shared on Slack
  - [x] Adds lines in .travis.yml to run codecov
  - [x] Fixes #6 
  - [x] Make sure Travis CI build passes or else this entire pull request is a failure

# Ready to Go:
  - [x] Ready to go

### CODE REVIEW

**Comment by kcpearce** [comment]
@amjames Review + Merge when you get a chance

**Comment by amjames** [comment]
@kcpearce are you sure? I'm confused since RTG is not checked.

**Comment by kcpearce** [comment]
@amjames I lied. I forgot to check that it passed the Travis CI build before asking for your review + merge

**Comment by kcpearce** [comment]
@amjames All things have passed. Review + Merge when you get a chance.

**Pull request merged**
